export enum Notes {
  'C' = 'C',
  'C#' = 'C#',
  'Db' = 'C#',
  'D' = 'D',
  'D#' = 'D#',
  'Eb' = 'D#',
  'E' = 'E',
  'F' = 'F',
  'F#' = 'F#',
  'Gb' = 'F#',
  'G' = 'G',
  'G#' = 'G#',
  'Ab' = 'G#',
  'A' = 'A',
  'A#' = 'A#',
  'Bb' = 'A#',
  'B' = 'B',
}

export enum Tones {
  'C#_Major' = '7#',
  'A#_Minor' = '7#',
  'F#_Major' = '6#',
  'D#_Minor' = '6#',
  'B_Major' = '5#',
  'G#_Minor' = '5#',
  'E_Major' = '4#',
  'C#_Minor' = '4#',
  'A_Major' = '3#',
  'F#_Minor' = '3#',
  'D_Major' = '2#',
  'B_Minor' = '2#',
  'G_Major' = '1#',
  'E_Minor' = '1#',
  'C_Major' = '0',
  'A_Minor' = '0',
  'F_Major' = '1b',
  'D_Minor' = '1b',
  'Bb_Major' = '2b',
  'G_Minor' = '2b',
  'Eb_Major' = '3b',
  'C_Minor' = '3b',
  'Ab_Major' = '4b',
  'F_Minor' = '4b',
  'Db_Major' = '5b',
  'Bb_Minor' = '5b',
  'Gb_Major' = '6b',
  'Eb_Minor' = '6b',
  'Cb_Major' = '7b',
  'Ab_Minor' = '7b',
}

export enum Modes {
  piano = 1,
  mic = 2,
}
